webpackJsonp([1], {
  /***/ 34: /***/ function(module, exports, __webpack_require__) {
    'use strict'
    eval(
      "\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\n\nvar _react = __webpack_require__(4);\n\nvar _react2 = _interopRequireDefault(_react);\n\nvar _reactRedux = __webpack_require__(21);\n\nvar _reduxFirstRouterLink = __webpack_require__(109);\n\nvar _reduxFirstRouterLink2 = _interopRequireDefault(_reduxFirstRouterLink);\n\nvar _Video = __webpack_require__(362);\n\nvar _Video2 = _interopRequireDefault(_Video);\n\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }\n\nvar Player = function Player(_ref) {\n  var playing = _ref.playing,\n      youtubeId = _ref.youtubeId,\n      slug = _ref.slug,\n      color = _ref.color;\n  return !playing ? _react2.default.createElement(\n    'div',\n    {\n      className: _Video2.default.heroContainer,\n      style: { backgroundImage: youtubeBackground(youtubeId) }\n    },\n    _react2.default.createElement(\n      _reduxFirstRouterLink2.default,\n      { to: '/video/' + slug + '/play' },\n      _react2.default.createElement('span', { className: 'ion-play', style: { backgroundColor: color } })\n    )\n  ) : _react2.default.createElement('iframe', {\n    className: _Video2.default.iframe,\n    frameBorder: '0',\n    allowFullScreen: true,\n    src: youtubeIframeSrc(youtubeId)\n  });\n};\n\nvar youtubeBackground = function youtubeBackground(youtubeId) {\n  return 'url(https://img.youtube.com/vi/' + youtubeId + '/maxresdefault.jpg)';\n};\n\nvar youtubeIframeSrc = function youtubeIframeSrc(youtubeId) {\n  return 'https://www.youtube.com/embed/' + youtubeId + '?playlist=' + youtubeId + '&autoplay=1&rel=0&theme=dark&loop=1&color=white&controls=2&autohide=1&showinfo=0';\n};\n\nvar _default = (0, _reactRedux.connect)(function (_ref2) {\n  var playing = _ref2.playing;\n  return { playing: playing };\n})(Player);\n\nexports.default = _default;\n;\n\nvar _temp = function () {\n  if (typeof __REACT_HOT_LOADER__ === 'undefined') {\n    return;\n  }\n\n  __REACT_HOT_LOADER__.register(Player, 'Player', '/Users/jamesgillmore/React/redux-first-router/examples/demo/src/components/Player.js');\n\n  __REACT_HOT_LOADER__.register(youtubeBackground, 'youtubeBackground', '/Users/jamesgillmore/React/redux-first-router/examples/demo/src/components/Player.js');\n\n  __REACT_HOT_LOADER__.register(youtubeIframeSrc, 'youtubeIframeSrc', '/Users/jamesgillmore/React/redux-first-router/examples/demo/src/components/Player.js');\n\n  __REACT_HOT_LOADER__.register(_default, 'default', '/Users/jamesgillmore/React/redux-first-router/examples/demo/src/components/Player.js');\n}();\n\n;\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/components/Player.js\n// module id = 34\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/components/Player.js?"
    )

    /***/
  },

  /***/ 362: /***/ function(module, exports, __webpack_require__) {
    eval(
      '// removed by extract-text-webpack-plugin\nmodule.exports = {"video":"Video__video--ir416","heroContainer":"Video__heroContainer--2ZQDs","iframe":"Video__iframe--qmSGK","infoContainer":"Video__infoContainer--XPYiD","videoTitle":"Video__videoTitle--piFpl","infoRow":"Video__infoRow--3eXXK","category":"Video__category--28p21","byText":"Video__byText--3pt-C","separator":"Video__separator--2T0IX","tipTitle":"Video__tipTitle--1XueQ","tip":"Video__tip--35bIx"};\nif (true) {\n\tmodule.hot.accept();\n\tif (module.hot.data) {\n\t\tvar neverUsed = 1512247205132\n\t\t__webpack_require__(22)("/static/", "Player.css");\n\t}\n}\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/css/Video.css\n// module id = 362\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/css/Video.css?'
    )

    /***/
  }
})
